services:
  python-script:
    image: python:3
    container_name: huai12138_bot
    working_dir: /usr/src/myapp
    network_mode: bridge
    ports:
      - 5005:5005
    volumes:
      - /root/huai12138_bot:/usr/src/myapp
    command: |
      sh -c "pip install -r requirements.txt && python app.py"
    restart: unless-stopped
    stdin_open: true # 等同于 -i
    tty: true # 等同于 -t
networks: {}
