services:
  Aria2-Pro:
    container_name: aria2-pro
    image: docker.io/p3terx/aria2-pro:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=1107530255
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/data/appdata/aria2:/config:Z
      - /mnt/user/data/Downloads:/downloads:Z
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp

  AriaNg:
    container_name: ariang
    image: docker.io/p3terx/ariang:latest
    command: --port 6880
    ports:
      - 6880:6880

