services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 5002:25500
    restart: unless-stopped
networks: {}
