services:
  SingBox-Subscribe:
    container_name: sing-box-subscribe
    image: hestudy/sing-box-subscribe
    network_mode: bridge
    ports:
      - 5000:5000
    volumes:
      - /mnt/user/data/appdata/sing-box-subscribe/config_template:/sing-box-subscribe/config_template
    restart: unless-stopped
networks: {}
