services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    cpu_period: 100000   # 默认值，0.1 秒
    cpu_quota: 200000    # 在 0.1 秒内最多使用 200000 微秒的 CPU 时间，相当于 2 个 CPU 核心
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - VERSION=docker
      - PLEX_CLAIM=
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/user/data/appdata/plex:/config:Z
      - /mnt/user/data/Downloads/media:/media:z
