services:
  vaultwarden:
    container_name: vaultwarden
    image: docker.io/vaultwarden/server:latest
    volumes:
      - /mnt/user/data/appdata/vaultwarden:/data:Z
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 8181:80
