services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - /mnt/user/data/appdata/vaultwarden:/data
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Asia/Shanghai
    network_mode: bridge
    ports:
      - 8181:80
    restart: unless-stopped
networks: {}
