services:
  zashboard:
    ports:
      - 9090:80
    image: ghcr.io/zephyruso/zashboard:latest
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: unless-stopped
networks: {}
