services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    network_mode: bridge
    ports:
      - 3001:3000
    volumes:
      - /mnt/user/data/appdata/homepage:/app/config # Make sure your local config directory exists
      - /mnt/user/data/appdata/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      - PUID=3000
      - PGID=100
      - TZ=Asia/Shanghai
    restart: unless-stopped
networks: {}
