services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3001:3000
    volumes:
      - /mnt/user/data/appdata/homepage:/app/config:Z # Make sure your local config directory exists
      - /mnt/user/data/appdata/homepage/icons:/app/public/icons:Z
      # - /run/user/1000/podman/podman.sock:/var/run/docker.sock # User-specific Podman socket
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - HOMEPAGE_ALLOWED_HOSTS=*


