services:
  nginx:
    image: docker.io/nginx:alpine
    container_name: nginx-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 80:80 # 映射 HTTP 端口
      - 443:443 # 映射 HTTPS 端口 (如果使用 SSL)
    volumes:
      - /mnt/user/data/appdata/nginx:/etc/nginx:Z # 挂载本地 Nginx 配置文件，添加 Z 标志用于 SELinux
      - /mnt/user/data/www:/usr/share/nginx/html:Z # 挂载本地 HTML 文件夹，添加 Z 标志
      - /mnt/user/data/appdata/nginx/logs:/var/log/nginx:Z # 启用日志目录挂载
    # userns_mode: "keep-id"
    # # user: "1000:1000"

