services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Asia/Shanghai
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /mnt/user/data/appdata/calibre:/config
      - /mnt/user/data/books:/books
      - /mnt/user/data/epub:/epub
    network_mode: bridge
    ports:
      - 8081:8080
    restart: unless-stopped
networks: {}
