services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /mnt/data/appdata/calibre:/config
      - /mnt/data/books:/books
      - /mnt/data/epub:/epub
    network_mode: bridge
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
networks: {}
