services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=3000
      - PGID=100
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /mnt/user/data/appdata/calibre:/config
      - /mnt/user/data/books:/books
      - /mnt/user/data/epub:/epub
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
networks: {}
