services:
  wordpress:
    image: docker.io/library/wordpress:latest
    ports:
      - 8088:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /mnt/user/data/appdata/wordpress:/var/www/html:Z
  db:
    image: docker.io/library/mysql:8.0
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - /mnt/user/data/appdata/db:/var/lib/mysql:Z

