services:
  music-tag:
    image: docker.io/xhongc/music_tag_web:latest
    container_name: music-tag-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 8002:8002
    volumes:
      - /mnt/user/data/Downloads/media/Music:/app/media:Z
      - /mnt/user/data/appdata/music_tag_web:/app/data:Z
      - /mnt/user/data/appdata/music_tag_web/ffmpeg/bin:/app/data/bin:Z
    #    command: /start

