version: "3"
services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 8002:8002
    volumes:
      - /mnt/data/media/Music:/app/media:rw
      - /mnt/data/appdata/music_tag_web:/app/data
    #    command: /start
    restart: unless-stopped
networks: {}
