services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    network_mode: bridge
    environment:
#      - PUID=3000
#      - PGID=3000
      - TZ=Asia/Shanghai
    ports:
      - 8002:8002
    volumes:
      - /mnt/user/data/media/downloads/Music:/app/media:rw
      - /mnt/user/data/appdata/music_tag_web:/app/data
    #    command: /start
    restart: unless-stopped
networks: {}
