version: "3.8"
services:
  node:
    image: node:22
    user: node
    working_dir: /home/node/app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - NODE_ENV=production
    volumes:
      - /mnt/data/appdata/node/app:/home/node/app
      - /mnt/data/appdata/node/.npm:/home/node/.npm
    expose:
      - "8081"
    network_mode: bridge
    ports:
      # use if it is necessary to expose the container to the host machine
      - 8001:8001
    command: npm start
    restart: unless-stopped
networks: {}
