version: '3.8'
services:
     web:
       container_name: httpd
       image: httpd
       network_mode: bridge
       ports:
         - "9999:80"
       volumes:
         - /mnt/user/data/www:/usr/local/apache2/htdocs/
       restart: unless-stopped