services:
  python-script:
    image: python:3
    container_name: mconline
    working_dir: /usr/src/myapp
    network_mode: bridge
    ports:
      - 5007:5007
    volumes:
      - /root/mconline:/usr/src/myapp
    command: |
      sh -c "pip install -r requirements.txt && python app.py"
    restart: unless-stopped
    stdin_open: true # 等同于 -i
    tty: true # 等同于 -t
networks: {}
