services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/data/appdata/jellyfin:/config:Z
      - /mnt/user/data/Downloads/media:/media:Z
      - /mnt/user/data/MiSans:/usr/local/share/fonts/truetype/MiSans:Z
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8097:8096
