services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/data/appdata/jellyfin:/config
      - /mnt/data/media:/data
      - /mnt/data/MiSans:/usr/local/share/fonts/truetype/MiSans
    devices:
      - /dev/dri:/dev/dri
    network_mode: bridge
    ports:
      - 8097:8096
    restart: unless-stopped
networks: {}
