version: "3.3"
services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    volumes:
      - /mnt/data/appdata/alist:/opt/alist/data
      - /mnt/data/:/mnt/data
    network_mode: bridge
    ports:
      - 5244:5244
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: unless-stopped
networks: {}
