services:
  python-script:
    image: python:3
    container_name: emby_webhooks
    working_dir: /usr/src/myapp
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Asia/Shanghai
    network_mode: bridge
    ports:
      - 5003:5003
    volumes:
      - /mnt/user/data/appdata/emby_webhooks:/usr/src/myapp
    command: |
      sh -c "pip install -r requirements.txt && python app.py"
    restart: unless-stopped
    stdin_open: true # 等同于 -i
    tty: true # 等同于 -t
networks: {}
