services:
  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - 8080:80
    volumes:
      - /mnt/user/data/www:/usr/local/apache2/htdocs/
      - /mnt/user/data/appdata/apache/conf:/usr/local/apache2/conf/
      - /mnt/user/data/logs/apache:/usr/local/apache2/logs
    restart: unless-stopped
networks: {}
