services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 8090:8090
    volumes:
      - /mnt/data/media/Music:/app/music
      - /mnt/data/appdata/xiaomusic/conf:/app/conf
networks: {}
