services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8080:80 # Public HTTP Port
      - 8443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DISABLE_IPV6: "true" # Keep this if IPv6 is disabled on your host
      #      PUID: 3000
      #      PGID: 3000
      TZ: Asia/Shanghai
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - /mnt/user/data/appdata/nginx-proxy-manager:/data
      - /mnt/user/data/appdata/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    # Removed networks: {} as it's not needed with bridge mode and explicit port mapping
networks: {}
